name: Send Hawks Result

on:
  schedule:
    - cron: '30 12 * * *'  # 日本時間21:30に実行（UTC換算）
  workflow_dispatch:        # 手動実行も可能

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install requests beautifulsoup4
      - run: python send_result.py
        env:
          LINE_TOKEN: ${{ secrets.LINE_TOKEN }}
